version: "1.0"
services:
  web:
    build: .
      # context: contextPath
      # dockerfile: Dockerfile
    ports:
      - "8000:5000"

  redis:
    image: "redis:${REDIS_TAG}"

  db:
    image: "postgres"
    ports: 
      - "8001:5432"
    environment:
      - POSTGRES_PASSWORD=superuserpassword